version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./main.py:/app/main.py
      - ./templates:/app/templates
    restart: no